data: data/now_youre_cooking/tiny/BPE_COPY
save_checkpoint_steps: 500
keep_checkpoint: 2
seed: 123
warmup_steps: 1000
train_steps: 10000
valid_steps: 100
report_every: 100

encoder_type: transformer
decoder_type: multi_src_transformer
word_vec_size: 768
rnn_size: 768
enc_layers: 4
dec_layers: 12
transformer_ff: 3072
heads: 12

accum_count: 7
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: stlr
learning_rate: 2e-3
max_grad_norm: 0.0
disc_ft: 1.2
dec_lr_factor: 5.0

batch_size: 2800
batch_type: tokens
normalization: tokens
dropout: 0.2
label_smoothing: 0.1

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
position_encoding_learned: 'true'
position_encoding_ctxsize: 1024
share_decoder_embeddings: 'true'
share_position_embeddings: 'true'
share_embeddings: 'true'

world_size: 1
gpu_ranks:
    - 0
    
tensorboard: 'true'

num_src: 2
include_agenda: 'true'
copy_attn: 'true'